# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build: # required for runs that dont use workflows

    working_directory: ~/incident-reporting-service

    docker:
      - image: circleci/python:3.7.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
          # DATABASE_URL: mysql://reportingservice:@localhost:3306/incident.reporting.service
          # DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/mysql:8.0.13
        environment:
          # MYSQL_USER: incident.reporting.service
          # MYSQL_DB: reportingservice
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: reportingservice
          MYSQL_USER: root
          MYSQL_PASSWORD: passw0rd
          MYSQL_HOST: localhost

    steps:
      - checkout
      # Download and cache dependencies
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          keys: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install --upgrade pip
            sudo pip install pipenv
            pipenv install

      - save_cache:
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.6/site-packages'
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      # run tests!

      - run:
          name: run tests
          command: |
            pipenv run python manage.py test

      # upload & store test result
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
