"""Type ORM layers the table that records the name of the types of bug report"""

from django.db import models


class Type(models.Model):
    """Types of reports"""
    name = models.CharField(max_length=100, default='')
    uuid = models.CharField(max_length=100, default='')  # New field. Uniquely generated by me.
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def generate_report(self):
        pass

    def get_bug_info(self):
        pass

    def get_issue_info(self):
        pass
